[package]
name = "pyline-libs"
version = "0.1.0"
authors.workspace = true
readme.workspace = true
keywords = ["analyzer", "code-analysis", "cli", "statistics", "code-quality"]
edition = "2024"
license.workspace = true
description = "Rust-powered tool for analyzing codebases with precise file filtering and keyword statistics."

[dependencies]
phf = { version = "0.14", features = ["macros"] }
rayon = "1"
thiserror = "2"
walkdir = "2"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }

[lints]
workspace = true
