//! Parser traits for language-specific implementations.

use crate::{collector::models::FileData, errors::PyLineError};

/// Interface for language-specific code parser.
///
/// Implementations are usually generated by
/// [`impl_lang_parser!`](crate::impl_lang_parser), which provides the
/// common file-handling and statistics logic. Language-specific line
/// parsing is implemented separately.
pub trait CodeParsers
where
    Self: Sized,
{
    /// Creates an empty parser.
    fn new() -> Self;

    /// Parses the given files, updating the accumulated statistics.
    ///
    /// # Errors
    ///
    /// Returns [`PyLineError`] if parsing fails and errors are not skipped.
    fn parse(&mut self, files: &[FileData]) -> Result<(), PyLineError>;

    /// Parses a single file, returning its statistics.
    ///
    /// # Errors
    ///
    /// Returns [`PyLineError`] if the file cannot be opened or parsed.
    fn parse_file(file: &FileData) -> Result<Self, PyLineError>;

    /// Merges `other` into `self`.
    fn merge(&mut self, other: Self);
}
