//! Parser traits for language-specific implementations.

use crate::{collector::models::FileData, errors::PyLineError};

/// Interface for language-specific code parser.
///
/// Implementations are usually generated by
/// [`impl_lang_parser!`](crate::impl_lang_parser), which provides the
/// common file-handling and statistics logic. Language-specific line
/// parsing is implemented separately.
pub trait CodeParsers {
    type Code: Default;

    /// Creates an empty parser.
    fn new() -> Self::Code {
        Default::default()
    }

    /// Parses the given files, updating the accumulated statistics.
    ///
    /// # Errors
    ///
    /// Returns [`PyLineError`] if parsing fails and errors are not skipped.
    fn parse(&mut self, files: &[FileData]) -> Result<(), PyLineError>;

    fn parse_file(file: &FileData) -> Result<Self::Code, PyLineError>;

    /// Merges `other` into `self`.
    fn merge(&mut self, other: Self::Code);
}
