//! Parser traits for language-specific implementations.

use crate::{collector::models::FileData, errors::PyLineError};

/// Interface for language-specific code parser.
///
/// Implementations are usually generated by
/// [`impl_lang_parser!`](crate::impl_lang_parser), which provides the
/// common file-handling and statistics logic. Language-specific line
/// parsing is implemented separately.
pub trait CodeParsers {
    type Code: Default;

    /// Creates an empty parser.
    fn new() -> Self::Code {
        Default::default()
    }

    /// Like [`Self::new`], but also increments the file counter.
    fn new_one() -> Self::Code;

    /// Merges `other` into `self`.
    fn merge(&mut self, other: Self::Code);

    /// Like [`Self::merge`], but takes `other` by reference.
    fn merge_ref(&mut self, other: &Self::Code);

    /// Parses the given files, updating the accumulated statistics.
    ///
    /// # Errors
    ///
    /// Returns [`PyLineError`] if parsing fails and errors are not skipped.
    fn parse(&mut self, files: &[FileData])
    -> impl Future<Output = Result<(), PyLineError>> + Send;

    /// Increments the total file counter.
    fn count_file(&mut self);

    /// Increments the invalid file counter.
    fn count_invalid_file(&mut self);

    /// Increments the total line counter.
    fn count_line(&mut self);

    /// Increments the total line counter.
    fn count_code_line(&mut self);
}
