use phf::phf_map;

pub const TECH_DIRS: &[&str] = &[
    "venv",
    ".venv",
    "env",
    ".env",
    "__pycache__",
    ".git",
    "mypy_cache",
    ".pytest_cache",
    ".idea",
    ".vscode",
    ".eggs",
    ".cache",
];

pub const VALID_EXTENSIONS: &[&str] = &["py"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyKeywords {
    False,
    None,
    True,
    And,
    As,
    Assert,
    Async,
    Await,
    Break,
    Class,
    Continue,
    Def,
    Del,
    Elif,
    Else,
    Except,
    Finally,
    For,
    From,
    Global,
    If,
    Import,
    In,
    Is,
    Lambda,
    Nonlocal,
    Not,
    Or,
    Pass,
    Raise,
    Return,
    Try,
    While,
    With,
    Yield,
}

pub(crate) static KEYWORDS: phf::Map<&'static str, PyKeywords> = phf_map! {
    "false" => PyKeywords::False,
    "none" => PyKeywords::None,
    "true" => PyKeywords::True,
    "and" => PyKeywords::And,
    "as" => PyKeywords::As,
    "assert" => PyKeywords::Assert,
    "async" => PyKeywords::Async,
    "await" => PyKeywords::Await,
    "break" => PyKeywords::Break,
    "class" => PyKeywords::Class,
    "continue" => PyKeywords::Continue,
    "def" => PyKeywords::Def,
    "del" => PyKeywords::Del,
    "elif" => PyKeywords::Elif,
    "else" => PyKeywords::Else,
    "except" => PyKeywords::Except,
    "finally" => PyKeywords::Finally,
    "for" => PyKeywords::For,
    "from" => PyKeywords::From,
    "global" => PyKeywords::Global,
    "if" => PyKeywords::If,
    "import" => PyKeywords::Import,
    "in" => PyKeywords::In,
    "is" => PyKeywords::Is,
    "lambda" => PyKeywords::Lambda,
    "nonlocal" => PyKeywords::Nonlocal,
    "not" => PyKeywords::Not,
    "or" => PyKeywords::Or,
    "pass" => PyKeywords::Pass,
    "raise" => PyKeywords::Raise,
    "return" => PyKeywords::Return,
    "try" => PyKeywords::Try,
    "while" => PyKeywords::While,
    "with" => PyKeywords::With,
    "yield" => PyKeywords::Yield,
};
